/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRegistryRouteImport } from './routes/partners-registry'
import { Route as PartnersJoinRouteImport } from './routes/partners-join'
import { Route as PartnersCooperationRouteImport } from './routes/partners-cooperation'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MsbRouteImport } from './routes/msb'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DirectionsRouteImport } from './routes/directions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'

const PartnersRegistryRoute = PartnersRegistryRouteImport.update({
  id: '/partners-registry',
  path: '/partners-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersJoinRoute = PartnersJoinRouteImport.update({
  id: '/partners-join',
  path: '/partners-join',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersCooperationRoute = PartnersCooperationRouteImport.update({
  id: '/partners-cooperation',
  path: '/partners-cooperation',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MsbRoute = MsbRouteImport.update({
  id: '/msb',
  path: '/msb',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsRoute = DirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directions': typeof DirectionsRoute
  '/finance': typeof FinanceRoute
  '/msb': typeof MsbRoute
  '/news': typeof NewsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/partners-cooperation': typeof PartnersCooperationRoute
  '/partners-join': typeof PartnersJoinRoute
  '/partners-registry': typeof PartnersRegistryRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directions': typeof DirectionsRoute
  '/finance': typeof FinanceRoute
  '/msb': typeof MsbRoute
  '/partners': typeof PartnersRoute
  '/partners-cooperation': typeof PartnersCooperationRoute
  '/partners-join': typeof PartnersJoinRoute
  '/partners-registry': typeof PartnersRegistryRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directions': typeof DirectionsRoute
  '/finance': typeof FinanceRoute
  '/msb': typeof MsbRoute
  '/news': typeof NewsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/partners-cooperation': typeof PartnersCooperationRoute
  '/partners-join': typeof PartnersJoinRoute
  '/partners-registry': typeof PartnersRegistryRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/directions'
    | '/finance'
    | '/msb'
    | '/news'
    | '/partners'
    | '/partners-cooperation'
    | '/partners-join'
    | '/partners-registry'
    | '/news/$slug'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/directions'
    | '/finance'
    | '/msb'
    | '/partners'
    | '/partners-cooperation'
    | '/partners-join'
    | '/partners-registry'
    | '/news/$slug'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/directions'
    | '/finance'
    | '/msb'
    | '/news'
    | '/partners'
    | '/partners-cooperation'
    | '/partners-join'
    | '/partners-registry'
    | '/news/$slug'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DirectionsRoute: typeof DirectionsRoute
  FinanceRoute: typeof FinanceRoute
  MsbRoute: typeof MsbRoute
  NewsRoute: typeof NewsRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PartnersCooperationRoute: typeof PartnersCooperationRoute
  PartnersJoinRoute: typeof PartnersJoinRoute
  PartnersRegistryRoute: typeof PartnersRegistryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners-registry': {
      id: '/partners-registry'
      path: '/partners-registry'
      fullPath: '/partners-registry'
      preLoaderRoute: typeof PartnersRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners-join': {
      id: '/partners-join'
      path: '/partners-join'
      fullPath: '/partners-join'
      preLoaderRoute: typeof PartnersJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners-cooperation': {
      id: '/partners-cooperation'
      path: '/partners-cooperation'
      fullPath: '/partners-cooperation'
      preLoaderRoute: typeof PartnersCooperationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msb': {
      id: '/msb'
      path: '/msb'
      fullPath: '/msb'
      preLoaderRoute: typeof MsbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions': {
      id: '/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof DirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DirectionsRoute: DirectionsRoute,
  FinanceRoute: FinanceRoute,
  MsbRoute: MsbRoute,
  NewsRoute: NewsRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PartnersCooperationRoute: PartnersCooperationRoute,
  PartnersJoinRoute: PartnersJoinRoute,
  PartnersRegistryRoute: PartnersRegistryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
